/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

#include "accessor.h"

#include "POUS.h"

// CONFIGURATION CONFIG0
__DECLARE_GLOBAL_LOCATION(BOOL,__IX0_0)
__DECLARE_GLOBAL_LOCATED(BOOL,CONFIG0,PB1)
__DECLARE_GLOBAL_LOCATION(BOOL,__QX0_0)
__DECLARE_GLOBAL_LOCATED(BOOL,CONFIG0,LED2)
__DECLARE_GLOBAL_LOCATION(BOOL,__QX0_1)
__DECLARE_GLOBAL_LOCATED(BOOL,CONFIG0,LED)

void RES0_init__(void);

void config_init__(void) {
  BOOL retain;
  retain = 0;
  __INIT_GLOBAL_LOCATED(CONFIG0,PB1,__IX0_0,retain)
  __INIT_GLOBAL(BOOL,PB1,__INITIAL_VALUE(__BOOL_LITERAL(FALSE)),retain)
  __INIT_GLOBAL_LOCATED(CONFIG0,LED2,__QX0_0,retain)
  __INIT_GLOBAL(BOOL,LED2,__INITIAL_VALUE(__BOOL_LITERAL(FALSE)),retain)
  __INIT_GLOBAL_LOCATED(CONFIG0,LED,__QX0_1,retain)
  __INIT_GLOBAL(BOOL,LED,__INITIAL_VALUE(__BOOL_LITERAL(FALSE)),retain)
  RES0_init__();
}

void RES0_run__(unsigned long tick);

void config_run__(unsigned long tick) {
  RES0_run__(tick);
}
unsigned long long common_ticktime__ = 50000000ULL * 1ULL; /*ns*/
unsigned long greatest_tick_count__ = (unsigned long)0UL; /*tick*/
