__DECLARE_GLOBAL_PROTOTYPE(BOOL,PB1)
__DECLARE_GLOBAL_PROTOTYPE(BOOL,PB2)
__DECLARE_GLOBAL_PROTOTYPE(BOOL,PB3)
__DECLARE_GLOBAL_PROTOTYPE(BOOL,LED)
__DECLARE_GLOBAL_PROTOTYPE(BOOL,LED2)
__DECLARE_GLOBAL_PROTOTYPE(BOOL,LED3)
__DECLARE_GLOBAL_PROTOTYPE(BOOL,LED4)

