#ifndef __POUS_H
#define __POUS_H

#include "accessor.h"
#include "iec_std_lib.h"

__DECLARE_ENUMERATED_TYPE(LOGLEVEL,
  LOGLEVEL__CRITICAL,
  LOGLEVEL__WARNING,
  LOGLEVEL__INFO,
  LOGLEVEL__DEBUG
)
// PROGRAM PROGRAM0
// Data part
typedef struct {
  // PROGRAM Interface - IN, OUT, IN_OUT variables

  // PROGRAM private variables - TEMP, private and located variables
  __DECLARE_LOCATED(BOOL,IX00)
  __DECLARE_LOCATED(BOOL,IX01)
  __DECLARE_LOCATED(BOOL,IX02)
  __DECLARE_LOCATED(BOOL,IX03)
  __DECLARE_LOCATED(BOOL,IX04)
  __DECLARE_LOCATED(BOOL,QX00)
  __DECLARE_LOCATED(BOOL,QX01)
  __DECLARE_LOCATED(BOOL,QX02)
  __DECLARE_LOCATED(BOOL,QX03)
  __DECLARE_LOCATED(BOOL,QX04)

} PROGRAM0;

void PROGRAM0_init__(PROGRAM0 *data__, BOOL retain);
// Code part
void PROGRAM0_body__(PROGRAM0 *data__);
#endif //__POUS_H
