//-----------------------------------------------------------------------------
// Copyright 2015 Thiago Alves
// This file is part of the OpenPLC Software Stack.
//
// OpenPLC is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// OpenPLC is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with OpenPLC.  If not, see <http://www.gnu.org/licenses/>.
//------
//
// This file is responsible for gluing the variables from the IEC program to
// the OpenPLC memory pointers. It is automatically generated by the
// glue_generator program. PLEASE DON'T EDIT THIS FILE!
// Thiago Alves, May 2016
//-----------------------------------------------------------------------------

#include "iec_std_lib.h"

TIME __CURRENT_TIME;
extern unsigned long long common_ticktime__;

//Internal buffers for I/O and memory. These buffers are defined in the
//auto-generated glueVars.cpp file
#define BUFFER_SIZE		1024

//Booleans
IEC_BOOL *bool_input[BUFFER_SIZE][8];
IEC_BOOL *bool_output[BUFFER_SIZE][8];

//Bytes
IEC_BYTE *byte_input[BUFFER_SIZE];
IEC_BYTE *byte_output[BUFFER_SIZE];

//Analog I/O
IEC_UINT *int_input[BUFFER_SIZE];
IEC_UINT *int_output[BUFFER_SIZE];

//32bit I/O
IEC_UDINT *dint_input[BUFFER_SIZE];
IEC_UDINT *dint_output[BUFFER_SIZE];

//64bit I/O
IEC_ULINT *lint_input[BUFFER_SIZE];
IEC_ULINT *lint_output[BUFFER_SIZE];

//Memory
IEC_UINT *int_memory[BUFFER_SIZE];
IEC_UDINT *dint_memory[BUFFER_SIZE];
IEC_ULINT *lint_memory[BUFFER_SIZE];

//Special Functions
IEC_ULINT *special_functions[BUFFER_SIZE];


#define __LOCATED_VAR(type, name, ...) type __##name;
#include "LOCATED_VARIABLES.h"
#undef __LOCATED_VAR
#define __LOCATED_VAR(type, name, ...) type* name = &__##name;
#include "LOCATED_VARIABLES.h"
#undef __LOCATED_VAR

void glueVars()
{
	bool_output[0][1] = (IEC_BOOL *)__QX0_1;
	bool_output[0][2] = (IEC_BOOL *)__QX0_2;
	bool_output[0][3] = (IEC_BOOL *)__QX0_3;
	bool_output[0][4] = (IEC_BOOL *)__QX0_4;
	bool_output[0][5] = (IEC_BOOL *)__QX0_5;
	bool_output[0][6] = (IEC_BOOL *)__QX0_6;
	bool_output[0][7] = (IEC_BOOL *)__QX0_7;
	bool_output[0][8] = (IEC_BOOL *)__QX0_8;
	bool_output[0][9] = (IEC_BOOL *)__QX0_9;
	bool_output[0][10] = (IEC_BOOL *)__QX0_10;
	bool_output[0][11] = (IEC_BOOL *)__QX0_11;
	bool_output[0][12] = (IEC_BOOL *)__QX0_12;
	bool_output[0][13] = (IEC_BOOL *)__QX0_13;
	bool_output[0][14] = (IEC_BOOL *)__QX0_14;
	bool_output[0][15] = (IEC_BOOL *)__QX0_15;
	bool_output[0][16] = (IEC_BOOL *)__QX0_16;
	bool_output[0][17] = (IEC_BOOL *)__QX0_17;
	bool_output[0][18] = (IEC_BOOL *)__QX0_18;
	bool_output[0][19] = (IEC_BOOL *)__QX0_19;
	bool_output[0][20] = (IEC_BOOL *)__QX0_20;
	bool_output[0][21] = (IEC_BOOL *)__QX0_21;
	bool_output[0][22] = (IEC_BOOL *)__QX0_22;
	bool_output[0][23] = (IEC_BOOL *)__QX0_23;
	bool_output[0][24] = (IEC_BOOL *)__QX0_24;
	bool_output[0][25] = (IEC_BOOL *)__QX0_25;
	bool_output[0][26] = (IEC_BOOL *)__QX0_26;
	bool_output[0][27] = (IEC_BOOL *)__QX0_27;
	bool_output[0][28] = (IEC_BOOL *)__QX0_28;
	bool_output[0][29] = (IEC_BOOL *)__QX0_29;
	bool_output[0][30] = (IEC_BOOL *)__QX0_30;
	bool_output[0][31] = (IEC_BOOL *)__QX0_31;
	bool_output[0][32] = (IEC_BOOL *)__QX0_32;
	bool_output[0][33] = (IEC_BOOL *)__QX0_33;
	bool_output[0][34] = (IEC_BOOL *)__QX0_34;
	bool_output[0][35] = (IEC_BOOL *)__QX0_35;
	bool_output[0][36] = (IEC_BOOL *)__QX0_36;
	bool_input[0][1] = (IEC_BOOL *)__IX0_1;
	bool_input[0][2] = (IEC_BOOL *)__IX0_2;
	bool_input[0][3] = (IEC_BOOL *)__IX0_3;
	bool_input[0][4] = (IEC_BOOL *)__IX0_4;
}

void updateTime()
{
	__CURRENT_TIME.tv_sec  += common_ticktime__ / 1000000000ULL;
	__CURRENT_TIME.tv_nsec += common_ticktime__ % 1000000000ULL;

	if (__CURRENT_TIME.tv_nsec >= 1000000000ULL)
	{
		__CURRENT_TIME.tv_nsec -= 1000000000ULL;
		__CURRENT_TIME.tv_sec += 1;
	}
}